/* MODALS */
export const MODAL_CLOSED = "MODAL_CLOSED";
export const MODAL_OPENED = "MODAL_OPENED";

/* INPUTS */
export const INPUT_CREATED = "INPUT_CREATED";
export const INPUT_DELETED = "INPUT_DELETED";
export const INPUT_UPDATED = "INPUT_UPDATED";

/* OBSERVERS */
export const OBSERVER_CREATED = "OBSERVER_CREATED";
export const OBSERVER_DELETED = "OBSERVER_DELETED";
export const OBSERVER_UPDATED = "OBSERVER_UPDATED";