export const CONSTANTS = {
  COLLECTION_SEARCH_FILE_COUNT: 10,
  COLLECTION_SEARCH_PAGE_SIZE: 50,
  DRAWER_WIDTH: 210,
  FILE_COUNT: 50,
  MONGOOSE_OPTS: { family: 4 },
  THUMB_FRAME_SKIP_PERCENT: 0.03,
  TOP_BAR_HEIGHT: "3rem",
  ZOOM_MAX_SCALE: 5,
  ZOOM_MIN_SCALE: 1,
  ZOOM_STEP: 0.1,
};
