/* --------------------------------------------------------------------------- */
/*                               THIS IS A GENERATED FILE. DO NOT EDIT.
/* --------------------------------------------------------------------------- */
import { initTRPC } from "@trpc/server";
import * as db from "medior/server/database/actions";
export const trpc = initTRPC.create();

/** All resources defined as mutation to deal with max length URLs in GET requests.
 *  @see https://github.com/trpc/trpc/discussions/1936
 */
export const serverEndpoint = <Input, Output>(fn: (input: Input) => Promise<Output>) =>
  trpc.procedure.input((input: Input) => input).mutation(({ input }) => fn(input));

export const serverRouter = trpc.router({
  /** Model actions */
  _createTag: serverEndpoint(db._createTag),
  _deleteTag: serverEndpoint(db._deleteTag),
  _updateFile: serverEndpoint(db._updateFile),
  createDeletedFile: serverEndpoint(db.createDeletedFile),
  createFile: serverEndpoint(db.createFile),
  createFileCollection: serverEndpoint(db.createFileCollection),
  createFileImportBatch: serverEndpoint(db.createFileImportBatch),
  deleteDeletedFile: serverEndpoint(db.deleteDeletedFile),
  deleteFile: serverEndpoint(db.deleteFile),
  deleteFileCollection: serverEndpoint(db.deleteFileCollection),
  deleteFileImportBatch: serverEndpoint(db.deleteFileImportBatch),
  listDeletedFile: serverEndpoint(db.listDeletedFile),
  listFile: serverEndpoint(db.listFile),
  listFileCollection: serverEndpoint(db.listFileCollection),
  listFileImportBatch: serverEndpoint(db.listFileImportBatch),
  listTag: serverEndpoint(db.listTag),
  updateDeletedFile: serverEndpoint(db.updateDeletedFile),
  updateFileCollection: serverEndpoint(db.updateFileCollection),
  updateFileImportBatch: serverEndpoint(db.updateFileImportBatch),
  updateTag: serverEndpoint(db.updateTag),
  /** Search store actions */
  getFilteredFileCollectionCount: serverEndpoint(db.getFilteredFileCollectionCount),
  getFilteredFileCount: serverEndpoint(db.getFilteredFileCount),
  getFilteredTagCount: serverEndpoint(db.getFilteredTagCount),
  getShiftSelectedFile: serverEndpoint(db.getShiftSelectedFile),
  getShiftSelectedFileCollection: serverEndpoint(db.getShiftSelectedFileCollection),
  getShiftSelectedTag: serverEndpoint(db.getShiftSelectedTag),
  listFilteredFile: serverEndpoint(db.listFilteredFile),
  listFilteredFileCollection: serverEndpoint(db.listFilteredFileCollection),
  listFilteredTag: serverEndpoint(db.listFilteredTag),
  /** Custom actions */
  addFilesToCollection: serverEndpoint(db.addFilesToCollection),
  completeImportBatch: serverEndpoint(db.completeImportBatch),
  createCollection: serverEndpoint(db.createCollection),
  createImportBatches: serverEndpoint(db.createImportBatches),
  createTag: serverEndpoint(db.createTag),
  deduplicateCollections: serverEndpoint(db.deduplicateCollections),
  deleteCollections: serverEndpoint(db.deleteCollections),
  deleteEmptyCollections: serverEndpoint(db.deleteEmptyCollections),
  deleteFiles: serverEndpoint(db.deleteFiles),
  deleteImportBatches: serverEndpoint(db.deleteImportBatches),
  deleteTag: serverEndpoint(db.deleteTag),
  deriveAncestorTagIds: serverEndpoint(db.deriveAncestorTagIds),
  deriveDescendantTagIds: serverEndpoint(db.deriveDescendantTagIds),
  detectFaces: serverEndpoint(db.detectFaces),
  editFileTags: serverEndpoint(db.editFileTags),
  editMultiTagRelations: serverEndpoint(db.editMultiTagRelations),
  editTag: serverEndpoint(db.editTag),
  emitImportStatsUpdated: serverEndpoint(db.emitImportStatsUpdated),
  getDeletedFile: serverEndpoint(db.getDeletedFile),
  getDiskStats: serverEndpoint(db.getDiskStats),
  getFileByHash: serverEndpoint(db.getFileByHash),
  getTagWithRelations: serverEndpoint(db.getTagWithRelations),
  importFile: serverEndpoint(db.importFile),
  listAllCollectionIds: serverEndpoint(db.listAllCollectionIds),
  listByLabels: serverEndpoint(db.listByLabels),
  listCollectionIdsByTagIds: serverEndpoint(db.listCollectionIdsByTagIds),
  listDeletedFiles: serverEndpoint(db.listDeletedFiles),
  listFaceModels: serverEndpoint(db.listFaceModels),
  listFileIdsByTagIds: serverEndpoint(db.listFileIdsByTagIds),
  listFileIdsForCarousel: serverEndpoint(db.listFileIdsForCarousel),
  listFilePaths: serverEndpoint(db.listFilePaths),
  listFilesByTagIds: serverEndpoint(db.listFilesByTagIds),
  listImportBatches: serverEndpoint(db.listImportBatches),
  listSortedFileIds: serverEndpoint(db.listSortedFileIds),
  listVideosWithMissingInfo: serverEndpoint(db.listVideosWithMissingInfo),
  loadFaceApiNets: serverEndpoint(db.loadFaceApiNets),
  makeAncestorIdsMap: serverEndpoint(db.makeAncestorIdsMap),
  mergeTags: serverEndpoint(db.mergeTags),
  recalculateTagCounts: serverEndpoint(db.recalculateTagCounts),
  refreshTag: serverEndpoint(db.refreshTag),
  refreshTagRelations: serverEndpoint(db.refreshTagRelations),
  regenCollAttrs: serverEndpoint(db.regenCollAttrs),
  regenCollTagAncestors: serverEndpoint(db.regenCollTagAncestors),
  regenFileTagAncestors: serverEndpoint(db.regenFileTagAncestors),
  regenTagAncestors: serverEndpoint(db.regenTagAncestors),
  regenTagThumbPaths: serverEndpoint(db.regenTagThumbPaths),
  regenTags: serverEndpoint(db.regenTags),
  relinkFiles: serverEndpoint(db.relinkFiles),
  repairFilesWithBrokenExt: serverEndpoint(db.repairFilesWithBrokenExt),
  repairFilesWithMissingInfo: serverEndpoint(db.repairFilesWithMissingInfo),
  repairTags: serverEndpoint(db.repairTags),
  repairThumbs: serverEndpoint(db.repairThumbs),
  setFileFaceModels: serverEndpoint(db.setFileFaceModels),
  setFileIsArchived: serverEndpoint(db.setFileIsArchived),
  setFileRating: serverEndpoint(db.setFileRating),
  setTagCount: serverEndpoint(db.setTagCount),
  startImportBatch: serverEndpoint(db.startImportBatch),
  updateCollection: serverEndpoint(db.updateCollection),
  updateFile: serverEndpoint(db.updateFile),
  updateFileImportByPath: serverEndpoint(db.updateFileImportByPath),
  upsertTag: serverEndpoint(db.upsertTag),
});
