/* -------------------------------------------------------------------------- */
/*                    THIS IS A GENERATED FILE. DO NOT EDIT.                  */
/* -------------------------------------------------------------------------- */

import { initTRPC } from "@trpc/server";
import * as db from "medior/database/actions";

export const trpc = initTRPC.create();

/** All resources defined as mutation to deal with max length URLs in GET requests.
 *  @see https://github.com/trpc/trpc/discussions/1936
 */
export const serverEndpoint = <Input, Output>(fn: (input: Input) => Promise<Output>) =>
  trpc.procedure.input((input: Input) => input).mutation(({ input }) => fn(input));

export const serverRouter = trpc.router({
  /** Model actions */
  createDeletedFile: serverEndpoint(db.createDeletedFile),
  deleteDeletedFile: serverEndpoint(db.deleteDeletedFile),
  _listDeletedFiles: serverEndpoint(db._listDeletedFiles),
  updateDeletedFile: serverEndpoint(db.updateDeletedFile),
  createFileCollection: serverEndpoint(db.createFileCollection),
  deleteFileCollection: serverEndpoint(db.deleteFileCollection),
  listFileCollections: serverEndpoint(db.listFileCollections),
  updateFileCollection: serverEndpoint(db.updateFileCollection),
  createFileImportBatch: serverEndpoint(db.createFileImportBatch),
  deleteFileImportBatch: serverEndpoint(db.deleteFileImportBatch),
  listFileImportBatchs: serverEndpoint(db.listFileImportBatchs),
  updateFileImportBatch: serverEndpoint(db.updateFileImportBatch),
  createFile: serverEndpoint(db.createFile),
  deleteFile: serverEndpoint(db.deleteFile),
  listFiles: serverEndpoint(db.listFiles),
  _updateFile: serverEndpoint(db._updateFile),
  createRegExMap: serverEndpoint(db.createRegExMap),
  deleteRegExMap: serverEndpoint(db.deleteRegExMap),
  listRegExMaps: serverEndpoint(db.listRegExMaps),
  updateRegExMap: serverEndpoint(db.updateRegExMap),
  _createTag: serverEndpoint(db._createTag),
  _deleteTag: serverEndpoint(db._deleteTag),
  _listTags: serverEndpoint(db._listTags),
  updateTag: serverEndpoint(db.updateTag),
  /** Custom actions */
  createCollection: serverEndpoint(db.createCollection),
  deleteCollection: serverEndpoint(db.deleteCollection),
  deleteEmptyCollections: serverEndpoint(db.deleteEmptyCollections),
  listAllCollectionIds: serverEndpoint(db.listAllCollectionIds),
  listCollectionIdsByTagIds: serverEndpoint(db.listCollectionIdsByTagIds),
  listFilteredCollections: serverEndpoint(db.listFilteredCollections),
  regenCollAttrs: serverEndpoint(db.regenCollAttrs),
  regenCollRating: serverEndpoint(db.regenCollRating),
  regenCollTagAncestors: serverEndpoint(db.regenCollTagAncestors),
  updateCollection: serverEndpoint(db.updateCollection),
  completeImportBatch: serverEndpoint(db.completeImportBatch),
  createImportBatches: serverEndpoint(db.createImportBatches),
  deleteImportBatches: serverEndpoint(db.deleteImportBatches),
  emitImportStatsUpdated: serverEndpoint(db.emitImportStatsUpdated),
  listImportBatches: serverEndpoint(db.listImportBatches),
  startImportBatch: serverEndpoint(db.startImportBatch),
  updateFileImportByPath: serverEndpoint(db.updateFileImportByPath),
  listFileIdsByTagIds: serverEndpoint(db.listFileIdsByTagIds),
  regenFileTagAncestors: serverEndpoint(db.regenFileTagAncestors),
  deleteFiles: serverEndpoint(db.deleteFiles),
  detectFaces: serverEndpoint(db.detectFaces),
  editFileTags: serverEndpoint(db.editFileTags),
  getDeletedFile: serverEndpoint(db.getDeletedFile),
  getDiskStats: serverEndpoint(db.getDiskStats),
  getFileByHash: serverEndpoint(db.getFileByHash),
  getShiftSelectedFiles: serverEndpoint(db.getShiftSelectedFiles),
  importFile: serverEndpoint(db.importFile),
  listDeletedFiles: serverEndpoint(db.listDeletedFiles),
  listFaceModels: serverEndpoint(db.listFaceModels),
  listFilesByTagIds: serverEndpoint(db.listFilesByTagIds),
  listFileIdsForCarousel: serverEndpoint(db.listFileIdsForCarousel),
  listFilePaths: serverEndpoint(db.listFilePaths),
  listFilteredFiles: serverEndpoint(db.listFilteredFiles),
  loadFaceApiNets: serverEndpoint(db.loadFaceApiNets),
  relinkFiles: serverEndpoint(db.relinkFiles),
  setFileFaceModels: serverEndpoint(db.setFileFaceModels),
  setFileIsArchived: serverEndpoint(db.setFileIsArchived),
  setFileRating: serverEndpoint(db.setFileRating),
  updateFile: serverEndpoint(db.updateFile),
  deriveAncestorTagIds: serverEndpoint(db.deriveAncestorTagIds),
  deriveDescendantTagIds: serverEndpoint(db.deriveDescendantTagIds),
  makeAncestorIdsMap: serverEndpoint(db.makeAncestorIdsMap),
  regenTags: serverEndpoint(db.regenTags),
  regenTagAncestors: serverEndpoint(db.regenTagAncestors),
  regenTagThumbPaths: serverEndpoint(db.regenTagThumbPaths),
  createTag: serverEndpoint(db.createTag),
  deleteTag: serverEndpoint(db.deleteTag),
  editTag: serverEndpoint(db.editTag),
  editMultiTagRelations: serverEndpoint(db.editMultiTagRelations),
  getShiftSelectedTags: serverEndpoint(db.getShiftSelectedTags),
  listFilteredTags: serverEndpoint(db.listFilteredTags),
  listTags: serverEndpoint(db.listTags),
  mergeTags: serverEndpoint(db.mergeTags),
  recalculateTagCounts: serverEndpoint(db.recalculateTagCounts),
  refreshTagRelations: serverEndpoint(db.refreshTagRelations),
  refreshTag: serverEndpoint(db.refreshTag),
  setTagCount: serverEndpoint(db.setTagCount),
  upsertTag: serverEndpoint(db.upsertTag),
});
