/* --------------------------------------------------------------------------- */
/*                               THIS IS A GENERATED FILE. DO NOT EDIT.
/* --------------------------------------------------------------------------- */
import { initTRPC } from "@trpc/server";
import * as db from "medior/server/database/actions";
export const trpc = initTRPC.create();

/** All resources defined as mutation to deal with max length URLs in GET requests.
 *  @see https://github.com/trpc/trpc/discussions/1936
 */
export const serverEndpoint = <Input, Output>(fn: (input: Input) => Promise<Output>) =>
  trpc.procedure.input((input: Input) => input).mutation(({ input }) => fn(input));

export const serverRouter = trpc.router({
  /** Model actions */
  _createTag: serverEndpoint(db._createTag),
  _deleteTag: serverEndpoint(db._deleteTag),
  createDeletedFile: serverEndpoint(db.createDeletedFile),
  createFile: serverEndpoint(db.createFile),
  createFileCollection: serverEndpoint(db.createFileCollection),
  createFileImportBatch: serverEndpoint(db.createFileImportBatch),
  createTagCategory: serverEndpoint(db.createTagCategory),
  deleteDeletedFile: serverEndpoint(db.deleteDeletedFile),
  deleteFile: serverEndpoint(db.deleteFile),
  deleteFileCollection: serverEndpoint(db.deleteFileCollection),
  deleteFileImportBatch: serverEndpoint(db.deleteFileImportBatch),
  deleteTagCategory: serverEndpoint(db.deleteTagCategory),
  listDeletedFile: serverEndpoint(db.listDeletedFile),
  listFile: serverEndpoint(db.listFile),
  listFileCollection: serverEndpoint(db.listFileCollection),
  listFileImportBatch: serverEndpoint(db.listFileImportBatch),
  listTag: serverEndpoint(db.listTag),
  listTagCategory: serverEndpoint(db.listTagCategory),
  updateDeletedFile: serverEndpoint(db.updateDeletedFile),
  updateFile: serverEndpoint(db.updateFile),
  updateFileCollection: serverEndpoint(db.updateFileCollection),
  updateFileImportBatch: serverEndpoint(db.updateFileImportBatch),
  updateTag: serverEndpoint(db.updateTag),
  updateTagCategory: serverEndpoint(db.updateTagCategory),
  /** Search store actions */
  getFilteredFileCollectionCount: serverEndpoint(db.getFilteredFileCollectionCount),
  getFilteredFileCount: serverEndpoint(db.getFilteredFileCount),
  getFilteredFileImportBatchCount: serverEndpoint(db.getFilteredFileImportBatchCount),
  getFilteredTagCount: serverEndpoint(db.getFilteredTagCount),
  getShiftSelectedFile: serverEndpoint(db.getShiftSelectedFile),
  getShiftSelectedFileCollection: serverEndpoint(db.getShiftSelectedFileCollection),
  getShiftSelectedFileImportBatch: serverEndpoint(db.getShiftSelectedFileImportBatch),
  getShiftSelectedTag: serverEndpoint(db.getShiftSelectedTag),
  listFilteredFile: serverEndpoint(db.listFilteredFile),
  listFilteredFileCollection: serverEndpoint(db.listFilteredFileCollection),
  listFilteredFileImportBatch: serverEndpoint(db.listFilteredFileImportBatch),
  listFilteredTag: serverEndpoint(db.listFilteredTag),
  /** Custom actions */
  addFilesToCollection: serverEndpoint(db.addFilesToCollection),
  checkFileImportHashes: serverEndpoint(db.checkFileImportHashes),
  completeImportBatch: serverEndpoint(db.completeImportBatch),
  copyFile: serverEndpoint(db.copyFile),
  createCollection: serverEndpoint(db.createCollection),
  createImportBatches: serverEndpoint(db.createImportBatches),
  createTag: serverEndpoint(db.createTag),
  deduplicateCollections: serverEndpoint(db.deduplicateCollections),
  deleteCollections: serverEndpoint(db.deleteCollections),
  deleteEmptyCollections: serverEndpoint(db.deleteEmptyCollections),
  deleteFiles: serverEndpoint(db.deleteFiles),
  deleteFilesExternal: serverEndpoint(db.deleteFilesExternal),
  deleteImportBatches: serverEndpoint(db.deleteImportBatches),
  deleteTag: serverEndpoint(db.deleteTag),
  deriveAncestorTagIds: serverEndpoint(db.deriveAncestorTagIds),
  deriveDescendantTagIds: serverEndpoint(db.deriveDescendantTagIds),
  detectFaces: serverEndpoint(db.detectFaces),
  editFileTags: serverEndpoint(db.editFileTags),
  editMultiTagRelations: serverEndpoint(db.editMultiTagRelations),
  editTag: serverEndpoint(db.editTag),
  getDeletedFile: serverEndpoint(db.getDeletedFile),
  getDiskStats: serverEndpoint(db.getDiskStats),
  getFileByHash: serverEndpoint(db.getFileByHash),
  getImportBatch: serverEndpoint(db.getImportBatch),
  getImporterStatus: serverEndpoint(db.getImporterStatus),
  getNextImportBatch: serverEndpoint(db.getNextImportBatch),
  getTagWithRelations: serverEndpoint(db.getTagWithRelations),
  importFile: serverEndpoint(db.importFile),
  listAllCollectionIds: serverEndpoint(db.listAllCollectionIds),
  listCollectionIdsByTagIds: serverEndpoint(db.listCollectionIdsByTagIds),
  listCollectionsByFileIds: serverEndpoint(db.listCollectionsByFileIds),
  listDeletedFiles: serverEndpoint(db.listDeletedFiles),
  listFaceModels: serverEndpoint(db.listFaceModels),
  listFileIdsByTagIds: serverEndpoint(db.listFileIdsByTagIds),
  listFileIdsForCarousel: serverEndpoint(db.listFileIdsForCarousel),
  listFilePaths: serverEndpoint(db.listFilePaths),
  listFilesByTagIds: serverEndpoint(db.listFilesByTagIds),
  listRegExMaps: serverEndpoint(db.listRegExMaps),
  listSortedFileIds: serverEndpoint(db.listSortedFileIds),
  listTagAncestorLabels: serverEndpoint(db.listTagAncestorLabels),
  listTagsByLabels: serverEndpoint(db.listTagsByLabels),
  listVideosWithMissingInfo: serverEndpoint(db.listVideosWithMissingInfo),
  loadFaceApiNets: serverEndpoint(db.loadFaceApiNets),
  makeAncestorIdsMap: serverEndpoint(db.makeAncestorIdsMap),
  mergeTags: serverEndpoint(db.mergeTags),
  pauseImporter: serverEndpoint(db.pauseImporter),
  recalculateTagCounts: serverEndpoint(db.recalculateTagCounts),
  refreshTag: serverEndpoint(db.refreshTag),
  refreshTagRelations: serverEndpoint(db.refreshTagRelations),
  regenCollAttrs: serverEndpoint(db.regenCollAttrs),
  regenCollTagAncestors: serverEndpoint(db.regenCollTagAncestors),
  regenFileTagAncestors: serverEndpoint(db.regenFileTagAncestors),
  regenTagAncestors: serverEndpoint(db.regenTagAncestors),
  regenTagThumbPaths: serverEndpoint(db.regenTagThumbPaths),
  regenTags: serverEndpoint(db.regenTags),
  reingestFolder: serverEndpoint(db.reingestFolder),
  relinkFiles: serverEndpoint(db.relinkFiles),
  repairFilesWithBrokenExt: serverEndpoint(db.repairFilesWithBrokenExt),
  repairFilesWithMissingInfo: serverEndpoint(db.repairFilesWithMissingInfo),
  repairTags: serverEndpoint(db.repairTags),
  repairThumbs: serverEndpoint(db.repairThumbs),
  resumeImporter: serverEndpoint(db.resumeImporter),
  runImportBatch: serverEndpoint(db.runImportBatch),
  searchTags: serverEndpoint(db.searchTags),
  setFileFaceModels: serverEndpoint(db.setFileFaceModels),
  setFileIsArchived: serverEndpoint(db.setFileIsArchived),
  setFileRating: serverEndpoint(db.setFileRating),
  setTagCount: serverEndpoint(db.setTagCount),
  startImportBatch: serverEndpoint(db.startImportBatch),
  updateCollection: serverEndpoint(db.updateCollection),
  updateFileImportByPath: serverEndpoint(db.updateFileImportByPath),
  upsertTag: serverEndpoint(db.upsertTag),
});
